-- CreateEnum
CREATE TYPE "StudyYear" AS ENUM ('BACHELOR_1', 'BACHELOR_2', 'BACHELOR_3', 'MASTER_1', 'MASTER_2');

-- CreateEnum
CREATE TYPE "StudyProgramme" AS ENUM ('ARCHITECTURE', 'BIOMEDICAL', 'COMMON_BACHELOR', 'CIVIL', 'CHEMICAL', 'COMPUTER_SCIENCE', 'CYBERSECURITY', 'DIGITAL_HUMANITIES', 'ELECTRICAL', 'ENERGY', 'ARTIFICIAL_INTELLIGENCE', 'MATERIALS', 'NANO', 'URBANISM', 'MATHEMATICAL', 'MECHANICAL');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "studyYear" "StudyYear",
ADD COLUMN     "studyProgrammes" "StudyProgramme"[] DEFAULT ARRAY[]::"StudyProgramme"[];
