import { cookies } from 'next/headers';
import { LOCALE_COOKIE, type LogistiekLocale } from './i18n-shared';

export { LOCALE_COOKIE, type LogistiekLocale } from './i18n-shared';

export async function getLocale(): Promise<LogistiekLocale> {
  const value = (await cookies()).get(LOCALE_COOKIE)?.value;
  return value === 'en' ? 'en' : 'nl';
}

export const copy = {
  nl: {
    navMaterial: 'Materiaal', navVan: 'Vervoer', navFlesserke: 'Flesserke', navReservations: 'Mijn reservaties', navManage: 'Beheer', signIn: 'Inloggen', site: 'vtk.be', profileMainSite: 'Naar vtk.be',
    footerTitle: 'Uitleendienst van VTK Logistiek', footerLead: 'Voor materiaal, vervoer en een vlotte organisatie van je VTK-activiteit.', questions: 'Vragen?',
    loginKicker: 'VTK Logistiek', loginTitle: 'Uitleendienst', loginAction: 'Inloggen op vtk.be', loginLead: 'Log in met je VTK-account om materiaal of vervoer te reserveren.',
    homeEyebrow: 'VTK Logistiek · Uitleendienst', homeTitle: 'Alles wat je nodig hebt,', homeAccent: 'geleend', homeLead: 'Reserveer materiaal of vervoer bij VTK Logistiek. Je vraagt aan, het team keurt goed, jij haalt af.', homeMaterial: 'Materiaal lenen', homeMaterialLead: 'Van boormachines tot geluidsinstallaties: kies je materiaal en de periode, en dien je aanvraag in.', homeMaterialCta: 'Bekijk de catalogus', homeVan: 'Vervoer', homeVanLead: 'Iets groots te vervoeren? Boek de kar, auto of bakfiets met chauffeur.', homeVanCta: 'Vraag een rit aan', homeReservations: 'Mijn reservaties', homeReservationsLead: 'Volg de status van je aanvragen op, betaal online en bekijk wat je nog moet terugbrengen.', homeReservationsCta: 'Naar mijn reservaties', howItWorks: 'Zo werkt het', stepChoose: 'Kies wat je nodig hebt', stepRequest: 'Dien je aanvraag in', stepReturn: 'Haal op en breng terug', infoKicker: 'Goed geregeld', infoTitle: 'Van eerste aanvraag tot', infoAccent: 'terugbrengen', infoLead: 'De uitleendienst is er voor je activiteiten, projecten en vervoer. Vraag tijdig aan: Logistiek controleert beschikbaarheid en helpt je verder met de praktische afspraken.',
    pageMaterialTitle: 'Materiaal', pageMaterialAccent: 'lenen', pageMaterialLead: 'Kies je periode en je materiaal, en dien je aanvraag in. Het team van Logistiek keurt elke aanvraag goed; VTK-evenementen hebben voorrang op het materiaal, dus vraag ruim op voorhand aan.', materialPaymentNote: 'Je betaalt na goedkeuring. Je krijgt de waarborg terug wanneer al het materiaal in goede staat is teruggebracht.',
    pageVanTitle: 'Boek', pageVanAccent: 'vervoer', pageVanLead: 'Iets groots te vervoeren? Boek de kar, auto of bakfiets van VTK. Een vrijwilliger van Logistiek rijdt; je rijdt dus nooit zelf, en je helpt zelf laden en lossen.', vanDriverInfo: 'Een vrijwilliger van Logistiek rijdt. Voorzie zelf 1 of 2 personen om te laden en lossen.', vanTimingInfo: 'Dien je aanvraag minstens twee weken vooraf in. VTK-activiteiten krijgen voorrang.', vanPaymentInfo: 'Na goedkeuring krijg je een chauffeur toegewezen en kun je betalen.',
    pageReservationsTitle: 'Mijn', pageReservationsAccent: 'reservaties',
    manageKicker: 'VTK Logistiek', manageTitle: 'Beheer uitleendienst', noAccess: 'Geen toegang', appTitle: 'VTK Uitleendienst', appDescription: 'Materiaal lenen en vervoer reserveren bij VTK Logistiek.',
    loginDefault: 'Log in met je VTK-account om materiaal of vervoer te reserveren.', loginMaterial: 'Log in met je VTK-account om materiaal te reserveren.', loginItem: 'Log in om het materiaal te bekijken.', loginReservations: 'Log in om je reservaties te bekijken.', loginReservation: 'Log in om je reservatie te bekijken.', loginVan: 'Log in met je VTK-account om vervoer te reserveren.', loginTrip: 'Log in om je rit te bekijken.', loginFlesserke: 'Log in met je VTK-account om flesserke te reserveren.', loginManage: 'Log in om het beheer van de uitleendienst te openen.',
  },
  en: {
    navMaterial: 'Equipment', navVan: 'Transport', navFlesserke: 'Flesserke', navReservations: 'My reservations', navManage: 'Manage', signIn: 'Sign in', site: 'vtk.be', profileMainSite: 'Go to vtk.be',
    footerTitle: 'Equipment service by VTK Logistics', footerLead: 'For equipment, transport and smooth organisation of your VTK activity.', questions: 'Questions?',
    loginKicker: 'VTK Logistics', loginTitle: 'Equipment service', loginAction: 'Sign in on vtk.be', loginLead: 'Sign in with your VTK account to reserve equipment or transport.',
    homeEyebrow: 'VTK Logistics · Equipment service', homeTitle: 'Everything you need,', homeAccent: 'on loan', homeLead: 'Book equipment or transport with VTK Logistics. Submit your request, let the team approve it, and collect it when ready.', homeMaterial: 'Borrow equipment', homeMaterialLead: 'From drills to sound systems: choose your equipment and dates, then submit your request.', homeMaterialCta: 'Browse the catalogue', homeVan: 'Transport', homeVanLead: 'Need to move something large? Book the trailer, car or cargo bike with a driver.', homeVanCta: 'Request a trip', homeReservations: 'My reservations', homeReservationsLead: 'Track your requests, pay online and see what still needs to be returned.', homeReservationsCta: 'View my reservations', howItWorks: 'How it works', stepChoose: 'Choose what you need', stepRequest: 'Submit your request', stepReturn: 'Collect and return it', infoKicker: 'Well organised', infoTitle: 'From first request to', infoAccent: 'returning it', infoLead: 'The equipment service is here for your activities, projects and transport. Request in good time: Logistics checks availability and helps with the practical details.',
    pageMaterialTitle: 'Borrow', pageMaterialAccent: 'equipment', pageMaterialLead: 'Choose your dates and equipment, then submit your request. The Logistics team approves every request; VTK events have priority, so request well in advance.', materialPaymentNote: 'You pay after approval. The deposit is returned when all equipment is returned in good condition.',
    pageVanTitle: 'Book', pageVanAccent: 'transport', pageVanLead: 'Need to move something large? Book the trailer, car or cargo bike from VTK. A Logistics volunteer drives, so you never drive yourself; you help load and unload.', vanDriverInfo: 'A Logistics volunteer drives. Provide 1 or 2 people to help load and unload.', vanTimingInfo: 'Submit your request at least two weeks in advance. VTK activities have priority.', vanPaymentInfo: 'After approval, a driver is assigned and you can pay.',
    pageReservationsTitle: 'My', pageReservationsAccent: 'reservations',
    manageKicker: 'VTK Logistics', manageTitle: 'Equipment service management', noAccess: 'Access denied', appTitle: 'VTK Equipment Service', appDescription: 'Borrow equipment and book the VTK van with Logistics.',
    loginDefault: 'Sign in with your VTK account to reserve equipment or transport.', loginMaterial: 'Sign in with your VTK account to reserve equipment.', loginItem: 'Sign in to view this item.', loginReservations: 'Sign in to view your reservations.', loginReservation: 'Sign in to view your reservation.', loginVan: 'Sign in with your VTK account to reserve transport.', loginTrip: 'Sign in to view your trip.', loginFlesserke: 'Sign in with your VTK account to reserve flesserke.', loginManage: 'Sign in to open the equipment service management.',
  },
} as const;
